### ISSUE TITLE
Utf8 decoding? problem

### ISSUE THREAD

**Issue by skial** [mandel59/unifill#3]
Hello, 

Using this [gist](https://gist.github.com/skial/2c9a03e34251727b3330), I _**think**_ unifill's Utf8 decoding method is incorrect, but I'm not sure **how**. 

Using any of the methods from `unifill.Unifill` does not result in a runtime error or an exception being thrown.

Many thanks,
Skial

**Comment by mandel59** [comment]
Thank you for reporting :wink:

`unifill.Utf8` provides O(1) “by-code-units” API, while `unifill.Unifill` provides O(N) “by-code-points” API  (where N is the given number of index), so it is excepted behavior that `Utf8.fromString('→φ«').codePointAt(1)` throws `InvalidCodeUnitSequence(1)` and `Utf8.fromString('→φ«').codePointAt(3)` returns `966`.
cf. http://www.slideshare.net/ryuseimandel59/haxe-vs-unicode-english

The usage of “by-code-units” API is similar to the Java String API. If you want to get the second code point of the UTF-8 code unit sequence, use `offsetByCodePoints` or `codePointWidthAt`:

```
var u = Utf8.fromString('→φ«');

trace(u.codePointAt(u.offsetByCodePoints(0, 1))); // 966

var i = 0;
while(i < u.length) {
    trace(u.codePointAt(i)); // 8594, 966, 171
    i += u.codePointWidthAt(i);
}
```

I'll continue to investigate why the js doesn't throw `InvalidCodeUnitSequence` but fails.

**Comment by skial** [comment]
Thanks for the quick reply and explanation, I appreciate it.

I'm glad I was misunderstanding the API _(and Unicode in general)_ and there was nothing wrong with the library :smile:
